version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: perplexica_web_1
      APP_PORT: 3000

  web:
    image: itzcrazykns1337/vane:v1.12.2@sha256:61f2bbf3386ff3df08911fb3de0e1893b04702a4d49ef13fbadbda937b47ab7c
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/app_data:/home/perplexica/data
      - ${APP_DATA_DIR}/data/uploads:/home/perplexica/uploads
