version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: code-server_server_1
      APP_PORT: 8080

  server:
    image: codercom/code-server:4.139.1@sha256:0c067c3cf09ed1830ce282387826be8feefef8a5828f462791c2df3f1007ee17
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
    environment:
      PASSWORD: $APP_PASSWORD
