version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: downtify_downtify_1
      APP_PORT: 8000

  downtify:
    image: ghcr.io/henriquesebastiao/downtify:2.11.0@sha256:2b3f37e872fa96705f0bb3319da5fe5cc7eba78a790c76a9d61365b05e5344c0
    stop_grace_period: 1m
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/downtify:/downloads
      - ${APP_DATA_DIR}/data:/data
