version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: downtify_downtify_1
      APP_PORT: 8000

  downtify:
    image: ghcr.io/henriquesebastiao/downtify:3.1.0@sha256:fa1ec39be35b8de29c9ca257631710beaec0cd51908b39ec2bb49b998e3d6a08
    stop_grace_period: 1m
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/downtify:/downloads
      - ${APP_DATA_DIR}/data:/data
