version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: downtify_downtify_1
      APP_PORT: 8000

  downtify:
    image: ghcr.io/henriquesebastiao/downtify:2.8.0@sha256:37e07e2fc05decce2dd1b2d1cbbb2a9c9b909d37f0c1cd61e868409168532b97
    stop_grace_period: 1m
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/downtify:/downloads
      - ${APP_DATA_DIR}/data:/data
