version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: zoraxy_server_1
      APP_PORT: 8000

  server:
    image: zoraxydocker/zoraxy:v3.3.3@sha256:229fd5bff4a6605b2f261dd66da8dddcfb98688b01c4034c117ed125c0605c45
    restart: on-failure
    ports:
      - 41080:80
      - 41443:443
    volumes:
      - ${APP_DATA_DIR}/data/config/:/opt/zoraxy/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      FASTGEOIP: "false"
      ZEROTIER: "false"
      DOCKER: "false"
      NOAUTH: "true"
