version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: fossflow_web_1
      APP_PORT: "80"

  web:
    image: stnsmith/fossflow:master-b69fc2e@sha256:c0813b19a9c8a3b8d13901de0e35edf7d9300ae8327a905ff520239d5624dafc
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/diagrams:/data/diagrams
    environment:
      - NODE_ENV=production
      - ENABLE_SERVER_STORAGE=true
      - STORAGE_PATH=/data/diagrams
      - ENABLE_GIT_BACKUP=false
