version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wallos_server_1
      APP_PORT: 80

  server:
    image: bellamy/wallos:5.4.2@sha256:316f26e13265958e7946ef98ff600516fddc51d698ee98bd1ae1577e5e00789f
    restart: on-failure
    stop_grace_period: 1m
    environment:
      TZ: Etc/UTC
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/www/html/db
      - ${APP_DATA_DIR}/data/logos:/var/www/html/images/uploads/logos
