version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: rotki_web_1
      APP_PORT: 80

  web:
    image: rotki/rotki:v1.43.2@sha256:4191bb890aa1ad39e84df5072d4c4d34c44c1736376706aaea0e540664aa7ab1
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/data:/data
      - ${APP_DATA_DIR}/data/logs:/logs
