version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: canary_web_1
      APP_PORT: 3000
      PROXY_AUTH_WHITELIST: "/api/*"

  backend:
    image: schjonhaug/canary-backend:v1.5.0-test-db42e33@sha256:c12398726cebb1b651bda96ce46cf149c88008e921d761f639fbe6745ffb57df
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      CANARY_NETWORK: mainnet
      CANARY_ELECTRUM_URL: tcp://$APP_ELECTRS_NODE_IP:$APP_ELECTRS_NODE_PORT
      CANARY_BIND_ADDRESS: 0.0.0.0:3001
      CANARY_DATA_DIR: /app/data
      CANARY_MODE: "self-hosted"
      CANARY_SYNC_INTERVAL: 60
      CANARY_MEMPOOL_PORT: ${APP_CANARY_MEMPOOL_PORT:-}
      CANARY_SELF_HOSTED_ADMIN_PASSWORD: ${APP_PASSWORD}
      JWT_SECRET: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data:/app/data

  web:
    image: schjonhaug/canary-frontend:v1.5.0-test-db42e33@sha256:72fc6f1def8d95a7df1614e1c143b274644010402d27a651da9062911e57b138
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      API_URL: http://canary_backend_1:3001
    depends_on:
      - backend
