version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: canary_web_1
      APP_PORT: 3000
      PROXY_AUTH_WHITELIST: "/api/*"

  backend:
    image: schjonhaug/canary-backend:v1.6.0@sha256:ae30a405c4af64bee5e65f79ba9f7c719e8fab08af72de3447a517ab5d6c9b2d
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      CANARY_NETWORK: mainnet
      CANARY_ELECTRUM_URL: tcp://$APP_ELECTRS_NODE_IP:$APP_ELECTRS_NODE_PORT
      CANARY_BIND_ADDRESS: 0.0.0.0:3001
      CANARY_DATA_DIR: /app/data
      CANARY_MODE: "self-hosted"
      CANARY_SYNC_INTERVAL: 60
      FRONTEND_URL: http://${DEVICE_DOMAIN_NAME}:${APP_PROXY_PORT}
      CANARY_MEMPOOL_PORT: ${APP_CANARY_MEMPOOL_PORT:-}
      CANARY_TX_EXPLORER_PLATFORM: umbrel
      CANARY_UMBREL_NTFY_URL: ${APP_CANARY_UMBREL_NTFY_URL:-}
      CANARY_SELF_HOSTED_ADMIN_PASSWORD: ${APP_PASSWORD}
      JWT_SECRET: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data:/app/data

  web:
    image: schjonhaug/canary-frontend:v1.6.0@sha256:32257f2d668a8b427b569e055bb3bd68dbf238380716a27b638a54ff87abd08b
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      API_URL: http://canary_backend_1:3001
    depends_on:
      - backend
