services:
  app_proxy:
    environment:
      APP_HOST: jupyterlab_server_1
      APP_PORT: 8888
      PROXY_AUTH_ADD: "false"

  server:
    image: quay.io/jupyter/base-notebook:lab-4.5.5@sha256:68c9ebb025a0686f29fff585de3f28807fd21798c74bebf733247777e939ff54
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token=${APP_PASSWORD}
    restart: on-failure
