services:
  app_proxy:
    environment:
      APP_HOST: jupyterlab_server_1
      APP_PORT: 8888
      PROXY_AUTH_ADD: "false"

  server:
    image: quay.io/jupyter/base-notebook:lab-4.6.1@sha256:52f436f74810f786446bba78af484e592f8256045e5bbc6c2cb90b041bd00de7
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token=${APP_PASSWORD}
    restart: on-failure
