version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: canary-mining_app_1
      APP_PORT: 8080

  app:
    image: schjonhaug/canary-mining:v1.0.0@sha256:28e81576865f6a3ba5ad7ac812b81f2ea856d5c1f3f71590ee7062aa7d1886c3
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    entrypoint: ["/bin/sh", "/start.sh"]
    volumes:
      - ${APP_DATA_DIR}/start.sh:/start.sh:ro
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_BITCOIN_DATA_DIR}:/root/.bitcoin:ro
    ports:
      - "3335:3335/tcp"
