version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: canary-mining_app_1
      APP_PORT: 8080

  app:
    image: schjonhaug/canary-mining:v1.0.0@sha256:762f5033e5cbca8a94b75bb6985fdec7971afe6b8927334d6275dddf842b59af
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    entrypoint: ["/bin/sh", "/start.sh"]
    volumes:
      - ${APP_DATA_DIR}/start.sh:/start.sh:ro
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_BITCOIN_DATA_DIR}:/root/.bitcoin:ro
    ports:
      - "3335:3335/tcp"
