version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-seedtool_app_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  app:
    image: dennysubke/seedtool:2.3.0@sha256:ab5a3bd42d7d4d0afc9c77ea9448e5d34244b66d7064eac75247601934fb90cc
    restart: on-failure
