version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: privatebin_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: privatebin/nginx-fpm-alpine:2.0.4@sha256:ed5b44740c4c8482b612a25dad6864df94ef4e57082e8d947801a5622637d2db
    user: "1000:1000"
    read_only: true
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/privatebin-data:/srv/data
