version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: l-town_app_1
      APP_PORT: 30300

  app:
    image: ghcr.io/besoeasy/l-town:20260414@sha256:b5d01b97d4ca66fc0b062568156a37dc7b7259bcde67c5345cc98443a181d75d
    restart: on-failure
