version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: super-productivity_web_1
      APP_PORT: 80

  web:
    image: johannesjo/super-productivity:v18.21.0@sha256:9695dd43bcd0f6c88b821b34a6b38e2d3e57d2602b140238ba82ef6faf77d2a7
    restart: on-failure
