version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: super-productivity_web_1
      APP_PORT: 80

  web:
    image: johannesjo/super-productivity:v18.21.2@sha256:7bf1dc87be356bb049c03782b62aa81f7ebc49a064bb4ae3934da868e05b3840
    restart: on-failure
