version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: super-productivity_web_1
      APP_PORT: 80

  web:
    image: johannesjo/super-productivity:v18.8.0@sha256:c739caca8e0c5e83ea4a6289884079ac49e0c3c87c7f95598b5a9fb10cc2d9c4
    restart: on-failure
