#!/usr/bin/env bash
set -euo pipefail

### Correct permissions for npm data directories

APP_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
APP_DATA_DIR="${APP_DIR}/data"

DESIRED_OWNER="1000:1000"

NPM_DATA_DIR="${APP_DATA_DIR}/npm-data"
LETSENCRYPT_DATA_DIR="${APP_DATA_DIR}/letsencrypt"

npm_correct_permission() {
	local -r path="${1}"

	if [[ -d "${path}" ]]; then
		chown -R "${DESIRED_OWNER}" "${path}"
	fi
}

npm_correct_permission "${NPM_DATA_DIR}"
npm_correct_permission "${LETSENCRYPT_DATA_DIR}"
