version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: notediscovery_web_1
      APP_PORT: 8000

  web:
    image: ghcr.io/gamosoft/notediscovery:0.27.0@sha256:c58d030c4c0a43c06e8dfe4b9301d1e9047f4d26047e7331539076b7fd56b43f
    user: 1000:1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 5s

