version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: notediscovery_web_1
      APP_PORT: 8000

  web:
    image: ghcr.io/gamosoft/notediscovery:0.31.1@sha256:a20909fb0ea554fdf1a1ad75d47c42b46dce5478013ed6cbf241aa56847316e1
    user: 1000:1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 5s

