#!/usr/bin/env bash
set -euo pipefail

# This script checks for existence of data/ data/db and data/logs directories and creates them + sets correct permissions if they don'>

# App directory is one level up from this script
APP_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)"
APP_DATA_DIR="${APP_DIR}/data"
APP_DATA_DB_DIR="${APP_DATA_DIR}/database"
DESIRED_OWNER="1000:1000"

set_correct_permissions() {
    local -r path="${1}"
    if [[ -d "${path}" ]]; then
        owner=$(stat -c "%u:%g" "${path}")
        if [[ "${owner}" != "${DESIRED_OWNER}" ]]; then
            chown -R "${DESIRED_OWNER}" "${path}"
        fi
    fi
}

create_directory_if_not_exists() {
    local -r dir="${1}"
    if [[ ! -d "${dir}" ]]; then
        mkdir -p "${dir}"
    fi
    set_correct_permissions "${dir}"
}

# Create directories if they don't exist
create_directory_if_not_exists "${APP_DATA_DIR}"
create_directory_if_not_exists "${APP_DATA_DB_DIR}"
