version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: firefly-iii-importer_importer_1
      APP_PORT: 8080

  importer:
    image: fireflyiii/data-importer:version-2.3.4@sha256:1379248292e1a0820e73714f3676b6de3909178c3017fce7aec0a9d20ffb8dec
    restart: on-failure
    environment:
      # firefly-iii container:
      - FIREFLY_III_URL=http://firefly-iii_server_1:8080
      - VANITY_URL=http://${DEVICE_DOMAIN_NAME}:30009
