version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: firefly-iii-importer_importer_1
      APP_PORT: 8080

  importer:
    image: fireflyiii/data-importer:version-2.3.2@sha256:4e2cbcb0d95c34850534a3772f1732c00f6412077db33b1863703a1b628bdc12
    restart: on-failure
    environment:
      # firefly-iii container:
      - FIREFLY_III_URL=http://firefly-iii_server_1:8080
      - VANITY_URL=http://${DEVICE_DOMAIN_NAME}:30009
