version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: firefly-iii-importer_importer_1
      APP_PORT: 8080

  importer:
    image: fireflyiii/data-importer:version-2.2.3@sha256:ab52bf9325466431af8b311e9879f0a271b1b555b34cb0e1115d0d10a4ef9665
    restart: on-failure
    environment:
      # firefly-iii container:
      - FIREFLY_III_URL=http://firefly-iii_server_1:8080
      - VANITY_URL=http://${DEVICE_DOMAIN_NAME}:30009
