version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: robosats_web_1
      APP_PORT: 12596

  web:
    image: recksato/robosats-client:v0.8.5-alpha@sha256:6aa0afea9f511d82faf8a7c953673d0d2a0a761f122ba1c86aa7d45ab914417e
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}