#!/usr/bin/env bash
set -euo pipefail

bash "$(dirname "${BASH_SOURCE[0]}")/pre-start"

# Clear cache after updating the app

echo "Clearing cache for twenty."
"${UMBREL_ROOT}/scripts/app" compose "${APP_ID}" run --rm server yarn command:prod cache:flush
echo "Successfully cleared the twenty cache."

echo "Running database migrations for twenty."
"${UMBREL_ROOT}/scripts/app" compose "${APP_ID}" run --rm server yarn database:migrate:prod
echo "Successfully run database migrations for twenty."

exit 0
