version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: n8n_server_1
      APP_PORT: 5678
      # Allow external clients to reach n8n webhook and form endpoints
      # Authentication can be configured on the corresponding n8n nodes
      # More details here: https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.webhook/
      # https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.formtrigger/
      PROXY_AUTH_WHITELIST: "/webhook-test/*,/webhook/*,/form-test/*,/form/*,/form-waiting/*"

  server:
    image: n8nio/n8n:2.35.7@sha256:166d7e3ca384afdffe75394bf00046c299d84a4bf17b19b35d6cf7773af0a147
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/home/node/.n8n
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
      # Used to set the url for editor, REST API & webhooks
      - N8N_HOST=$DEVICE_DOMAIN_NAME
      - N8N_SECURE_COOKIE=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PROXY_HOPS=1
