version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: sabnzbd_web_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api*"

  web:
    image: linuxserver/sabnzbd:5.0.1@sha256:87c97fa81966adb5cf511ae62b6681a37136c32f1ad7190b0b8b4d12d766ea9f
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=ffmpeg
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
