version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: sabnzbd_web_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api*"

  web:
    image: linuxserver/sabnzbd:5.1.3@sha256:7f173ced3541b46c57c4eb6854765243095c8c8a7563a878044fa0ccfb1f4004
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=ffmpeg
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
