#!/usr/bin/env bash
set -euo pipefail

# v3.0.0 allowed the seerr container to run as non-root: https://github.com/seerr-team/seerr/releases/tag/v3.0.0
# Jellyseerr / Seerr previously ran as root, so we now recursively set the owner of the data directory to 1000:1000 so that pre-3.0.0 users do not have a broken app
APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"

# Recursively set ownership of all files and directories under APP_DATA_DIR to 1000:1000
chown -R 1000:1000 "${APP_DATA_DIR}"
