version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bentopdf_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/alam00000/bentopdf:v2.6.0@sha256:96709a7ecd64a3fb4adf4dcf320808248a565993ea0c67febd25da12a34dcab7
    restart: on-failure
