version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bentopdf_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/alam00000/bentopdf:v2.8.8@sha256:6ef493c8e3bdbaa26c9bfcec330377ae95116fa00660ca0342769063197b1952
    restart: on-failure
