version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bentopdf_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/alam00000/bentopdf:v2.4.1@sha256:699ff80f3c8eb46cdf9fc87d7d69ec79ff50a4ad384f6b3283b767bd88f15e54
    restart: on-failure
