version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: donetick_app_1
      APP_PORT: 2021
      PROXY_AUTH_ADD: "false"

  app:
    image: donetick/donetick:v0.1.80@sha256:eb94251e1a22d1613b2cc05546509461e708f30c6ae02e0907c4a6d44ceaa18c
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/app:/donetick-data
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
