version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: donetick_app_1
      APP_PORT: 2021
      PROXY_AUTH_ADD: "false"

  app:
    image: donetick/donetick:v0.1.76@sha256:2f32646ef4e613f44066163646f53c02d6d5b728b31abe47dfd111b3dfd53643
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/app:/donetick-data
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
