version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: element_web_1
      APP_PORT: 80

  web:
    image: vectorim/element-web:v1.12.21@sha256:26546ef29e02a6e0978c137b7cc93581e6bbb94a5fe95104b89a216c43004d12
    user: "nginx:nginx"
    restart: on-failure
    stop_grace_period: 1m
