version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: element_web_1
      APP_PORT: 80

  web:
    image: vectorim/element-web:v1.12.23@sha256:2a65f32acc6fd7163523d1c4b5174de354b5ceb085898b15898f4d8ea01a8e3d
    user: "nginx:nginx"
    restart: on-failure
    stop_grace_period: 1m
