version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: termix_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/lukegus/termix:release-1.11.1@sha256:aca304385f759b3d8b302fe56f9fd5dc5cd4f9bde636d454c08f7a38375197a9
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
