version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: termix_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/lukegus/termix:release-2.2.1@sha256:577c0e7024fa7767ffbd00e19a1e0ce28fb0027aab37c3f7d49e2c18bc001210
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
