#DR ABSTRACTS CLN_REST_BITCOIN_NETWORK="${APP_BITCOIN_NETWORK}" OS build HARD-CODE
export APP_CLN_REST_BITCOIN_NETWORK="bitcoin"
export APP_CORE_LIGHTNING_REST_MACAROON_PATH="${APP_DATA_DIR}/data/lightningd/bitcoin/rest/access.macaroon"
