#!/usr/bin/env node

/**
 * Caddy HTTPS Proxy - Web UI Server
 * Provides a web interface for configuring the Caddy proxy
 */

const http = require('http');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const { promisify } = require('util');

const execAsync = promisify(exec);

const PORT = process.env.WEB_PORT || 8080;
const APP_DATA_DIR = process.env.APP_DATA_DIR || '/data';
const CADDY_CONFIG_DIR = path.join(APP_DATA_DIR, 'caddy');
const CERTS_DIR = path.join(APP_DATA_DIR, 'certs');

// Configuration file paths
const CONFIG_FILE = path.join(APP_DATA_DIR, 'config.json');
const CADDYFILE = path.join(CADDY_CONFIG_DIR, 'Caddyfile');

// Default configuration
const defaultConfig = {
    domain: 'umbrel.local',
    httpsPort: 8443,
    httpPort: 8080,
    forceHttps: true,
    hsts: true,
    disableHttp: false,
    caddyfile: ''
};

// Load configuration from file
function loadConfig() {
    try {
        if (fs.existsSync(CONFIG_FILE)) {
            const data = fs.readFileSync(CONFIG_FILE, 'utf8');
            return { ...defaultConfig, ...JSON.parse(data) };
        }
    } catch (error) {
        console.error('Error loading config:', error);
    }
    return defaultConfig;
}

// Save configuration to file
function saveConfig(config) {
    try {
        fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2), 'utf8');
        return true;
    } catch (error) {
        console.error('Error saving config:', error);
        return false;
    }
}

// Generate Caddyfile from configuration
function generateCaddyfile(config) {
    let caddyfile = `# Auto-generated Caddyfile\n`;
    caddyfile += `# Generated by Caddy HTTPS Proxy Web UI\n\n`;
    
    caddyfile += `{\n`;
    caddyfile += `    http_port ${config.httpPort}\n`;
    caddyfile += `    https_port ${config.httpsPort}\n`;
    caddyfile += `    auto_https off\n`;
    caddyfile += `    admin 0.0.0.0:2019\n`;
    caddyfile += `}\n\n`;
    
    caddyfile += `:${config.httpsPort} {\n`;
    caddyfile += `    tls ${CERTS_DIR}/umbrel.crt ${CERTS_DIR}/umbrel.key\n\n`;
    
    if (config.hsts) {
        caddyfile += `    header {\n`;
        caddyfile += `        Strict-Transport-Security "max-age=31536000; includeSubDomains"\n`;
        caddyfile += `        X-Content-Type-Options "nosniff"\n`;
        caddyfile += `        X-Frame-Options "DENY"\n`;
        caddyfile += `        X-XSS-Protection "1; mode=block"\n`;
        caddyfile += `    }\n\n`;
    }
    
    // Add custom routes from user configuration
    if (config.caddyfile && config.caddyfile.trim()) {
        caddyfile += `    # Custom routes\n`;
        caddyfile += config.caddyfile.split('\n').map(line => `    ${line}`).join('\n');
        caddyfile += `\n\n`;
    }
    
    // Default welcome route
    caddyfile += `    handle / {\n`;
    caddyfile += `        respond "Welcome to Umbrel HTTPS Proxy!\\n\\nAccess your apps at:\\nhttps://${config.domain}:${config.httpsPort}/\\n\\nTo configure routing, use the Web UI." 200\n`;
    caddyfile += `    }\n`;
    
    caddyfile += `}\n\n`;
    
    if (!config.disableHttp && config.forceHttps) {
        caddyfile += `:${config.httpPort} {\n`;
        caddyfile += `    redir https://${config.domain}:${config.httpsPort}{uri} permanent\n`;
        caddyfile += `}\n`;
    } else if (!config.disableHttp) {
        caddyfile += `:${config.httpPort} {\n`;
        caddyfile += `    respond "HTTP access enabled. Redirect to HTTPS is disabled."\n`;
        caddyfile += `}\n`;
    }
    
    return caddyfile;
}

// Restart Caddy container
async function restartCaddy() {
    try {
        await execAsync('docker restart umbrel-caddy-https-app_caddy_1');
        return true;
    } catch (error) {
        console.error('Error restarting Caddy:', error);
        return false;
    }
}

// Get app status
async function getAppStatus() {
    try {
        const { stdout } = await execAsync('docker inspect -f {{.State.Status}} umbrel-caddy-https-app_caddy_1');
        const status = stdout.trim();
        return {
            running: status === 'running',
            status: status
        };
    } catch (error) {
        return {
            running: false,
            status: 'unknown'
        };
    }
}

// Regenerate certificates
async function regenerateCertificates() {
    try {
        const domain = loadConfig().domain || 'umbrel.local';
        
        // Remove existing certificates
        const certPath = path.join(CERTS_DIR, 'umbrel.crt');
        const keyPath = path.join(CERTS_DIR, 'umbrel.key');
        
        if (fs.existsSync(certPath)) fs.unlinkSync(certPath);
        if (fs.existsSync(keyPath)) fs.unlinkSync(keyPath);
        
        // Generate new certificates
        const opensslCmd = `openssl req -x509 -nodes -days 3650 -newkey rsa:2048 ` +
            `-keyout ${keyPath} -out ${certPath} ` +
            `-subj "/CN=${domain}/O=Umbrel/C=US" ` +
            `-addext "subjectAltName=DNS:${domain},DNS:*.${domain},IP:127.0.0.1"`;
        
        await execAsync(opensslCmd);
        
        // Set permissions
        await execAsync(`chmod 644 ${certPath}`);
        await execAsync(`chmod 600 ${keyPath}`);
        
        return true;
    } catch (error) {
        console.error('Error regenerating certificates:', error);
        return false;
    }
}

// Parse request body
function parseBody(req) {
    return new Promise((resolve, reject) => {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            try {
                resolve(body ? JSON.parse(body) : {});
            } catch (error) {
                reject(error);
            }
        });
        req.on('error', reject);
    });
}

// Serve static file
function serveFile(res, filePath, contentType) {
    fs.readFile(filePath, (err, data) => {
        if (err) {
            res.writeHead(500);
            res.end('Error reading file');
            return;
        }
        res.writeHead(200, { 'Content-Type': contentType });
        res.end(data);
    });
}

// Create HTTP server
const server = http.createServer(async (req, res) => {
    // CORS headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    
    if (req.method === 'OPTIONS') {
        res.writeHead(200);
        res.end();
        return;
    }
    
    const url = new URL(req.url, `http://localhost:${PORT}`);
    const pathname = url.pathname;
    
    try {
        // API Routes
        if (pathname === '/api/config' && req.method === 'GET') {
            const config = loadConfig();
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify(config));
            return;
        }
        
        if (pathname === '/api/config' && req.method === 'POST') {
            const body = await parseBody(req);
            const config = { ...defaultConfig, ...body };
            
            // Save configuration
            if (saveConfig(config)) {
                // Generate and save Caddyfile
                const caddyfile = generateCaddyfile(config);
                fs.writeFileSync(CADDYFILE, caddyfile);
                
                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ success: true }));
            } else {
                res.writeHead(500, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ error: 'Failed to save configuration' }));
            }
            return;
        }
        
        if (pathname === '/api/status' && req.method === 'GET') {
            const status = await getAppStatus();
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify(status));
            return;
        }
        
        if (pathname === '/api/restart' && req.method === 'POST') {
            const success = await restartCaddy();
            res.writeHead(success ? 200 : 500, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ success }));
            return;
        }
        
        if (pathname === '/api/certificate' && req.method === 'POST') {
            const success = await regenerateCertificates();
            res.writeHead(success ? 200 : 500, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ success }));
            return;
        }
        
        if (pathname === '/api/certificate/info' && req.method === 'GET') {
            try {
                const certPath = path.join(CERTS_DIR, 'umbrel.crt');
                const { stdout } = await execAsync(`openssl x509 -in ${certPath} -noout -enddate`);
                const expiryDate = stdout.replace('notAfter=', '').trim();
                
                const expiry = new Date(expiryDate);
                const now = new Date();
                const daysUntilExpiry = Math.floor((expiry - now) / (1000 * 60 * 60 * 24));
                
                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({
                    expiry: expiryDate,
                    daysUntilExpiry: daysUntilExpiry,
                    warning: daysUntilExpiry < 30
                }));
            } catch (error) {
                res.writeHead(500);
                res.end('Failed to read certificate');
            }
            return;
        }
        
        if (pathname === '/api/certificate/upload' && req.method === 'POST') {
            const contentType = req.headers['content-type'] || '';
            const boundaryMatch = contentType.match(/boundary=(?:"([^"]+)"|([^;]+))/i);
            
            if (!boundaryMatch) {
                res.writeHead(400, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ error: 'Invalid content type' }));
                return;
            }
            
            const boundary = '--' + (boundaryMatch[1] || boundaryMatch[2]);
            let body = '';
            
            req.on('data', chunk => { body += chunk; });
            req.on('end', async () => {
                try {
                    const parts = body.split(boundary);
                    let certBuffer = null;
                    let keyBuffer = null;
                    
                    for (const part of parts) {
                        if (!part.trim() || part === '--') continue;
                        
                        const lines = part.split('\r\n');
                        const headerMatch = lines[1]?.match(/name="([^"]+)"/);
                        if (!headerMatch) continue;
                        
                        const fieldName = headerMatch[1];
                        const fileData = part.split('\r\n\r\n')[1];
                        
                        if (fileData) {
                            const buffer = Buffer.from(fileData, 'binary');
                            if (fieldName === 'cert') certBuffer = buffer;
                            if (fieldName === 'key') keyBuffer = buffer;
                        }
                    }
                    
                    if (!certBuffer || !keyBuffer) {
                        res.writeHead(400, { 'Content-Type': 'application/json' });
                        res.end(JSON.stringify({ error: 'Missing cert or key file' }));
                        return;
                    }
                    
                    const certPath = path.join(CERTS_DIR, 'umbrel.crt');
                    const keyPath = path.join(CERTS_DIR, 'umbrel.key');
                    
                    fs.writeFileSync(certPath, certBuffer);
                    fs.writeFileSync(keyPath, keyBuffer);
                    await execAsync(`chmod 600 ${keyPath}`);
                    
                    res.writeHead(200, { 'Content-Type': 'application/json' });
                    res.end(JSON.stringify({ success: true }));
                } catch (error) {
                    console.error('Upload error:', error);
                    res.writeHead(500, { 'Content-Type': 'application/json' });
                    res.end(JSON.stringify({ error: 'Failed to save files' }));
                }
            });
            return;
        }
        
        // Serve web UI
        if (pathname === '/') {
            serveFile(res, path.join(__dirname, 'web', 'index.html'), 'text/html');
            return;
        }
        
        // Serve static assets
        if (pathname.startsWith('/assets/')) {
            const filePath = path.join(__dirname, 'web', pathname);
            const ext = path.extname(filePath);
            const contentTypes = {
                '.css': 'text/css',
                '.js': 'application/javascript',
                '.png': 'image/png',
                '.svg': 'image/svg+xml'
            };
            
            if (contentTypes[ext]) {
                serveFile(res, filePath, contentTypes[ext]);
                return;
            }
        }
        
        // 404
        res.writeHead(404);
        res.end('Not Found');
        
    } catch (error) {
        console.error('Error handling request:', error);
        res.writeHead(500);
        res.end('Internal Server Error');
    }
});

// Start server
server.listen(PORT, () => {
    console.log(`Caddy HTTPS Proxy Web UI running on port ${PORT}`);
    console.log(`Access at: http://localhost:${PORT}`);
});
