services:
  app_proxy:
    environment:
      APP_HOST: navidrome_server_1
      APP_PORT: 4533
      PROXY_AUTH_ADD: "false"

  server:
    image: deluan/navidrome:0.63.0@sha256:60080f8f7bfa039348820852a7f06a5615a0bb4f83bfe541e57cbb0a8650ec9e
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music
