#!/usr/bin/env bash

# APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/"
APP_DATA_DIR="/home/umbrel/umbrel/app-data/samba"

password=$(cat "${APP_DATA_DIR}/last-password")

# restore password on container
sed -i "s/\(PASS:\s*\).*\$/\1$password/" "${APP_DATA_DIR}/docker-compose.yml"

# restore password for Umbrel home
sed -i "s/\(defaultPassword:\s*\).*\$/\1$password/" "${APP_DATA_DIR}/umbrel-app.yml"
