version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: originless_app_1
      APP_PORT: 3232

  app:
    image: ghcr.io/besoeasy/originless:1.0.0@sha256:eb87d9a7a5363374a92c589eb6fad479fd2aa38203d5566d914b73a093e6a43c
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "3232:3232/udp"
    volumes:
      - ${APP_DATA_DIR}/data:/data
