version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: trip_app_1
      APP_PORT: 8000

  app:
    image: ghcr.io/itskovacs/trip:1.48.0@sha256:216cce2f829a54023d69cead7f5bba9b904ba59e98d4edf553b0a8a673eeae89
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/app:/app/storage
    command: ["fastapi", "run", "/app/trip/main.py", "--host", "0.0.0.0"]
