version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: trip_app_1
      APP_PORT: 8000

  app:
    image: ghcr.io/itskovacs/trip:1.45.0@sha256:cd202afceb10760f79fd1eba4a3cd91ddb7d36284e84e5d9e8adcd0f2eb06cbf
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/app:/app/storage
    command: ["fastapi", "run", "/app/trip/main.py", "--host", "0.0.0.0"]
