version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: trip_app_1
      APP_PORT: 8000

  app:
    image: ghcr.io/itskovacs/trip:1.46.0@sha256:83496be4e83cebb00f49959d4b7b1ca7d17b32352bc92c826ee143e8beec96c2
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/app:/app/storage
    command: ["fastapi", "run", "/app/trip/main.py", "--host", "0.0.0.0"]
