version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitbalance_app_1
      APP_PORT: 3710

  app:
    image: ghcr.io/egzola/bitbalance:1.0.18@sha256:9d390c1aa9025a49c37604239700662236b8fc84138ae582fa66710ac4a82bf7
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: 3710
      ELECTRUM_HOST: $APP_ELECTRS_NODE_IP
      ELECTRUM_PORT: $APP_ELECTRS_NODE_PORT
    volumes:
      - ${APP_DATA_DIR}/data:/data
