version: "3.7"

services:
  
  app_proxy:
    environment:
      APP_HOST: grafana_web_1
      APP_PORT: 3000
      PROXY_AUTH_WHITELIST: "/api/*"
      
  web:
    image: grafana/grafana:13.0.3@sha256:1a345428a36270f5fb9add69fea71450a5843c15266c99359d6d380470ab19c9
    user: 1000:1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/grafana
