#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../data)"
ORDINALS_DATA_DIR="${APP_DATA_DIR}/ord"
DESIRED_OWNER="1000:1000"

set_correct_permissions() {
	local -r path="${1}"

	if [[ -d "${path}" ]]; then
		owner=$(stat -c "%u:%g" "${path}")

		if [[ "${owner}" != "${DESIRED_OWNER}" ]]; then
			chown -R "${DESIRED_OWNER}" "${path}"
		fi
	fi
}

if [[ -f "${APP_DATA_DIR}/index.redb" ]]; then
  rm -f "${APP_DATA_DIR}/index.redb"
  mkdir -p "${ORDINALS_DATA_DIR}"
  # set correct permissions for both data and ord
  set_correct_permissions "${APP_DATA_DIR}"
fi

# re-index the ordinals data for runes
if [[ ! -f "${APP_DATA_DIR}/INDEXED_0-17-1" ]]; then
	rm -f "${ORDINALS_DATA_DIR}/index.redb"
	touch "${APP_DATA_DIR}/INDEXED_0-17-1"
fi





