version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lubelogger_app_1
      APP_PORT: 8080

  app:
    image: ghcr.io/hargata/lubelogger:v1.6.5@sha256:293604d85b021b6489ef3d0b22c792cefcc802bf8eec0b5c4766a4a979b8a998
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/app:/App/data
      - ${APP_DATA_DIR}/data/keys:/root/.aspnet/DataProtection-Keys
