version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lubelogger_app_1
      APP_PORT: 8080

  app:
    image: ghcr.io/hargata/lubelogger:v1.6.8@sha256:82093696a6cfd73c3b6678e6233acb25e9979604ee9659faa3f955e6895ba191
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/app:/App/data
      - ${APP_DATA_DIR}/data/keys:/root/.aspnet/DataProtection-Keys
