version: "3.7"

services:
  server:
    image: homeassistant/home-assistant:2026.5.4@sha256:ceb1202133a5a036e8b03e20a10eb113186cc2f871968323c6fc6c3fc4205716
    network_mode: host
    # UI at default port 8123
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/media
      - /dev:/dev
      - /run/dbus:/run/dbus:ro
