version: "3.7"

services:
  server:
    image: homeassistant/home-assistant:2026.8.1@sha256:6340a3de3917a9b19368e767310a96dd090f6a19aca8aeadf87fd1145cec9682
    network_mode: host
    # UI at default port 8123
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/media
      - /dev:/dev
      - /run/dbus:/run/dbus:ro
