version: "3.7"

services:
  server:
    image: homeassistant/home-assistant:2026.8.2@sha256:56690a89c79a0de98035e1719f8324a92d5859c1192ff45adb0230ea81cb42a5
    network_mode: host
    # UI at default port 8123
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/media
      - /dev:/dev
      - /run/dbus:/run/dbus:ro
