version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: nostr-vpn_web_1
      APP_PORT: 38080

  daemon:
    image: ghcr.io/mmalmi/nostr-vpn-umbrel:v4.0.58@sha256:cf51622fcc1a794ac80e1962fce0855f21575b1d3f69750cb90de82ee3fb52b5
    restart: on-failure
    stop_grace_period: 1m
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    entrypoint:
      - /usr/local/bin/nvpn
    command:
      - daemon
      - --config
      - /data/config/nvpn/config.toml
    environment:
      HOME: /data/home
      XDG_CONFIG_HOME: /data/config
      RUST_LOG: info
    volumes:
      - ${APP_DATA_DIR}/data:/data

  web:
    image: ghcr.io/mmalmi/nostr-vpn-umbrel:v4.0.58@sha256:cf51622fcc1a794ac80e1962fce0855f21575b1d3f69750cb90de82ee3fb52b5
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - daemon
    environment:
      HOME: /data/home
      XDG_CONFIG_HOME: /data/config
      NVPN_CLI_PATH: /usr/local/bin/nvpn
      NVPN_DAEMON_STATUS_MODE: state-file
      NVPN_EXTERNAL_DAEMON: "true"
      RUST_LOG: info
    volumes:
      - ${APP_DATA_DIR}/data:/data
