version: "3.7"

services:
  web:
    image: ghcr.io/music-assistant/server:2.9.6@sha256:4c2992c3cd9b5f26e82a97c196e19b1d3f5ed037df01f4fd26aa0e15799d2539
    restart: on-failure
    user: "1000:1000"
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    # UI at data/settings.json defined port 8896
    # Streamserver at default port 8078
    # Sendspin at default port 8927
    volumes:
      - ${APP_DATA_DIR}/data:/data/
      - ${UMBREL_ROOT}/data/storage/downloads:/media
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor=unconfined
