version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: homarr_web_1
      APP_PORT: 7575

  web:
    image: ghcr.io/homarr-labs/homarr:v1.76.0@sha256:1a47c2afd892d8939b49195a7098fcbe44f4ac15a74b9ba02ed2de237089542f
    restart: on-failure
    environment:
      SECRET_ENCRYPTION_KEY: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data:/appdata
