version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: homarr_web_1
      APP_PORT: 7575

  web:
    image: ghcr.io/homarr-labs/homarr:v2.0.0@sha256:3eeef80bfc58f6588844e9405da47550f681006d3019005a34f9388b5c00eb73
    restart: on-failure
    environment:
      AUTH_SECRET: ${APP_SEED}
      SECRET_ENCRYPTION_KEY: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data:/appdata
