version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: homarr_web_1
      APP_PORT: 7575

  web:
    image: ghcr.io/homarr-labs/homarr:v1.69.1@sha256:fbc43fc086b2095a1f008316f673ebb2d846c995514bd7426fcd97cb161187fe
    restart: on-failure
    environment:
      SECRET_ENCRYPTION_KEY: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data:/appdata
