#!/usr/bin/env bash

# This pre-start script copies the default config if there is no config given.
# If you want to start with new default config, you have to un- and reinstall the app.

APP_DATA_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
CONFIG_FILE="${APP_DATA_DIR}/data/config/mosquitto.conf"

if [ -f "${CONFIG_FILE}" ]; then
  echo "configuration file present, nothing will be changed."
else
  echo "configuration file NOT present, defaults will be copied."
  cp "${CONFIG_FILE}.default" "${CONFIG_FILE}"
  # set correct owner
  chown umbrel:umbrel "${CONFIG_FILE}"
fi
