version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: am-i-exposed_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/copexit/am-i-exposed-umbrel:v0.37.1@sha256:5f1b1b6055ccd756faeb7c88f0b0a9ae62bfe0703804a05de5e59439a1dd054a
    user: "101:101"
    init: true
    restart: on-failure
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health || exit 1"]
      interval: 30s
      timeout: 3s
    environment:
      APP_MEMPOOL_IP: ${APP_MEMPOOL_IP}
      APP_MEMPOOL_PORT: ${APP_MEMPOOL_PORT}
      APP_MEMPOOL_HIDDEN_SERVICE: ${APP_MEMPOOL_HIDDEN_SERVICE}
      APP_TOR_PROXY_IP: tor-proxy
      APP_TOR_PROXY_PORT: "3001"
    depends_on:
      - tor-proxy

  tor-proxy:
    image: ghcr.io/copexit/am-i-exposed-tor-proxy:v0.37.1@sha256:281b25805909ef444ec45d36f3422312622f6f741d97546035da0310be63eda2
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 10s
    environment:
      PORT: "3001"
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
