version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: am-i-exposed_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/copexit/am-i-exposed-umbrel:v0.38.2@sha256:05a6c34ccc152c34ab8718bf9f3344e6b70005ef812772b32b151276067746de
    user: "101:101"
    init: true
    restart: on-failure
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health || exit 1"]
      interval: 30s
      timeout: 3s
    environment:
      APP_MEMPOOL_IP: ${APP_MEMPOOL_IP}
      APP_MEMPOOL_PORT: ${APP_MEMPOOL_PORT}
      APP_MEMPOOL_HIDDEN_SERVICE: ${APP_MEMPOOL_HIDDEN_SERVICE}
      APP_TOR_PROXY_IP: tor-proxy
      APP_TOR_PROXY_PORT: "3001"
    depends_on:
      - tor-proxy

  tor-proxy:
    image: ghcr.io/copexit/am-i-exposed-tor-proxy:v0.38.2@sha256:5e5edd5a960d7f650ce3cf2c4c1b9879f76e9e90186edfb8add036c4f602597c
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 10s
    environment:
      PORT: "3001"
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
