#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"

# Create required directories
mkdir -p "${APP_DATA_DIR}/uploads"
mkdir -p "${APP_DATA_DIR}/db"



chown -R 1000:1000 "${APP_DATA_DIR}" 2>/dev/null || true
