version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: mazanoke_web_1
      APP_PORT: 80

  web:
    image: ghcr.io/civilblur/mazanoke:v1.1.6@sha256:92cc7474deb789af6549318563b7a9ee750131f9f7b297cc9c87ab67e656c22c
    # does not work rootless
    #user: "1000:1000"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
