version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: mazanoke_web_1
      APP_PORT: 80

  web:
    image: ghcr.io/civilblur/mazanoke:v1.1.7@sha256:ca83cddd90cd1e4b43102884bf39025731a1c7569f3bbda9d6530de72528cbab
    # does not work rootless
    #user: "1000:1000"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
