version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: torbrowser_web_1
      APP_PORT: 5800
  web:
    image: dennysubke/torbrowser:15.0.17@sha256:b0c12dbc6b93338ef02f57186f47a57952f864e31f015a9fb47fa6c5afc0d0b1
    restart: on-failure
    environment:
      - DARK_MODE=1
      - WEB_AUDIO=1
    volumes:
      - ${APP_DATA_DIR}/config:/config
