#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)"
UMBREL_ROOT="${APP_DATA_DIR}/../.."

# We need to ensure Umbrel's shared download folder
# exists and is owned by the correct user
UMBREL_DATA_DIR="${UMBREL_ROOT}/data"
UMBREL_DATA_STORAGE_DIR="${UMBREL_DATA_DIR}/storage"
UMBREL_DATA_STORAGE_DOWNLOADS_DIR="${UMBREL_DATA_STORAGE_DIR}/downloads"
DESIRED_OWNER="1000:1000"

if [[ ! -d "${UMBREL_DATA_STORAGE_DOWNLOADS_DIR}" ]]; then
	mkdir -p "${UMBREL_DATA_STORAGE_DOWNLOADS_DIR}"
fi

simpletorrent_correct_permission() {
	local -r path="${1}"

	if [[ -d "${path}" ]]; then
		owner=$(stat -c "%u:%g" "${path}")

		if [[ "${owner}" != "${DESIRED_OWNER}" ]]; then
			chown "${DESIRED_OWNER}" "${path}"
		fi
	fi
}

simpletorrent_correct_permission "${UMBREL_DATA_DIR}"
simpletorrent_correct_permission "${UMBREL_DATA_STORAGE_DIR}"
simpletorrent_correct_permission "${UMBREL_DATA_STORAGE_DOWNLOADS_DIR}"

# Migrate existing installations to use the shared downloads directory
LOCAL_DOWNLOADS_DIR="${APP_DATA_DIR}/data/downloads"

if [[ ! -d "${LOCAL_DOWNLOADS_DIR}" ]]; then
	echo "No local downloads directory found. Skipping migration..."
	exit
fi

# Move contents of local downloads folder to Umbrel's shared downloads folder
rsync -vau --remove-source-files --exclude=".*" "${LOCAL_DOWNLOADS_DIR}/" "${UMBREL_DATA_STORAGE_DOWNLOADS_DIR}/"

rm -rf "${LOCAL_DOWNLOADS_DIR}"

echo "Local downloads directory successfully migrated"