version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: openreader_web_1
      APP_PORT: 3003

  web:
    image: ghcr.io/richardr1126/openreader:4.1.0@sha256:2569e5efa3466aa2d47b4671b76e026472c38a37c0779dc9c214947ec3b0acbd
    user: "1000:1000"
    command: ["node_modules/.bin/next", "start", "-p", "3003"]
    environment:
      - API_BASE=http://kokoro_web_1:8880/v1 #Set the TTS API_BASE URL and/or API_KEY as the default for all devices. These values can also be overridden in the UI.
      - BASE_URL=http://${DEVICE_DOMAIN_NAME}:3391
      - AUTH_SECRET=${APP_SEED}
      # Allows auth requests from the primary .local URL, device hostname, Tailscale FQDNs, and host IP URLs.
      - AUTH_TRUSTED_ORIGINS=http://${DEVICE_DOMAIN_NAME}:3391,http://${DEVICE_HOSTNAME}:3391,http://*.ts.net:3391,https://*.ts.net:3391,${APP_OPENREADER_LOCAL_URLS}
      - USE_ANONYMOUS_AUTH_SESSIONS=true
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/docstore:/app/docstore
