version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jackett_server_1
      APP_PORT: 9117
      PROXY_AUTH_WHITELIST: "/api/* /dl/*"

  server:
    image: linuxserver/jackett:0.24.1392@sha256:e77b8fa33cb528542638d858e5f70c470b9d05dadc41130b72c50b8058efa969
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
