version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jackett_server_1
      APP_PORT: 9117
      PROXY_AUTH_WHITELIST: "/api/* /dl/*"

  server:
    image: linuxserver/jackett:0.24.2404@sha256:bdde094b662158f3fd93d640dcf30f20e901cfc0b9a47ff3c338b9400cd6b5d7
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
