version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jackett_server_1
      APP_PORT: 9117
      PROXY_AUTH_WHITELIST: "/api/* /dl/*"

  server:
    image: linuxserver/jackett:0.24.2360@sha256:2434d2d33da5a75dd6846baa644a6e06f2d0bc3aa819350624285adadc9134f8
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
