version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: changedetection-io_app_1
      APP_PORT: 5000

  app:
    image: ghcr.io/dgtlmoon/changedetection.io:0.60.8@sha256:34df3680db1cbffc45ac1e9c1514bc0507dd0c5b5fde47d1992fe6f14a7b40e4
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      BASE_URL: http://${DEVICE_DOMAIN_NAME}:5037
      USE_X_SETTINGS: "1"
      HIDE_REFERER: "true"
      TZ: "Etc/UTC"
      DISABLE_VERSION_CHECK: "true"
    volumes:
      - ${APP_DATA_DIR}/data:/datastore
