version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: kokoro_web_1
      APP_PORT: 8880

  web:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.3.0@sha256:d7df384acb57929f88a696d892c1a2e0c6b60fa934802ebec9a88626003b8e9a
    user: "1000:1000"
    restart: on-failure
