version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: file-browser_server_1
      APP_PORT: 80

  server:
    image: filebrowser/filebrowser:v2.61.1@sha256:751252db58b56a23179f8ab19a4c4188792e86806e63737aa25999ef5d2b0c01
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/database/
      - ${APP_DATA_DIR}/data:/config/
      - ${UMBREL_ROOT}/data/storage:/data
    environment:
      - FB_PORT=80
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/data
      - FB_NOAUTH=true
