version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: file-browser_server_1
      APP_PORT: 80

  server:
    image: filebrowser/filebrowser:v2.63.9@sha256:bf6a77a330c0690da1ee2769e1c49e8194c61bd8aeffa97964dc71476b912017
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/database/
      - ${APP_DATA_DIR}/data:/config/
      - ${UMBREL_ROOT}/data/storage:/data
    environment:
      - FB_PORT=80
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/data
      - FB_NOAUTH=true
