version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: webcheck_server_1
      APP_PORT: 3000
  server:
    image: ghcr.io/lissy93/web-check:2.2.0@sha256:455bf61b5cb69b48e1ce600d05ad294fff5a1b8a60b361c54b4893edab6ec496
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
