version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: webcheck_server_1
      APP_PORT: 3000
  server:
    image: ghcr.io/lissy93/web-check:2.1.0@sha256:f15934b73da05bef3993bf1a62e110c100158b5105d8571229960e1d509c5c77
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
