version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: librespeed_server_1
      APP_PORT: 8080

  server:
    image: ghcr.io/librespeed/speedtest:6.3.0@sha256:af011d4fb5709c6e2b2f381925a6c290d53ce2ed35fa8860e7d33e20690d5065
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
