version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: yucca_yucca_1
      APP_PORT: 9910
      PROXY_AUTH_WHITELIST: "/v1/*"

  yucca:
    image: yuccastream/yucca:0.13.0@sha256:dc0aa25eaf0d1a3e957e9741dd6d52f9770ff427b2fc799b2888a9446838ff49
    restart: on-failure
    shm_size: "128mb"
    working_dir: /opt/yucca
    volumes:
      - "${APP_DATA_DIR}/data/data:/opt/yucca/data"
    ports:
      - 10925:10925 # SMTP server
      - 9912:9912 # telemetry (prometheus)
    environment: # Read more about configuration here https://docs.yucca.app/en/configuration/
      YUCCA_SERVER_DATA_DIR: "/opt/yucca/data"
      YUCCA_SMTP_SERVER_LISTEN_ADDRESS: ":10925"
