version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gupt_web_1
      APP_PORT: 8000

  web:
    image: ghcr.io/besoeasy/gupt:4.1.13@sha256:b0f15a2075bed76a9420ad7d128f92774077bf2bbd60fb6ce8816b24ee5dc48b
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
