version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gupt_web_1
      APP_PORT: 8000

  web:
    image: ghcr.io/besoeasy/gupt:5.0.9@sha256:5738fde2b3c9c6f8af800544fc401f8e9c7134add824bc5992e712dba21f214b
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
