version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gupt_web_1
      APP_PORT: 8000

  web:
    image: ghcr.io/besoeasy/gupt:2.70.0@sha256:c3b79966ea4b386bb01d8ee2e7c9e0705bf2d58e8d9a36dd3506dcf4d82bcca1
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
