services:
  app_proxy:
    environment:
      APP_HOST: papra_server_1
      APP_PORT: 1221
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: ghcr.io/papra-hq/papra:26.4.0-rootless@sha256:1de52370c82d0eb9aad101f5f06b92272cbae850f0ca3dc623fc96835f57ad68
    user: 1000:1000
    restart: on-failure
    environment:
      - AUTH_SECRET=${APP_SEED}
      - APP_BASE_URL=http://${DEVICE_DOMAIN_NAME}:8112
    volumes:
      - ${APP_DATA_DIR}/data:/app/app-data
