version: "3.7"

services:
    app_proxy:
        environment:
            APP_HOST: kapowarr_kapowarr_1
            APP_PORT: 5656

    kapowarr:
        image: mrcas/kapowarr:v1.3.1@sha256:d455797e4f2c5b1a8ccc5ce05c427f1af2179451bb1af195ca3fa8c3e928623b
        volumes:
            - ${APP_DATA_DIR}/data/db:/app/db
            - ${UMBREL_ROOT}/data/storage/downloads:/app/temp_downloads
        restart: on-failure
