version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: hermes-agent_web_1
      APP_PORT: 9119

  server:
    image: nousresearch/hermes-agent:latest@sha256:b9f289194f7d2003745f2e8449c85c2d2ae6672d56f6e62f5fecf2e94edc6b8c
    command:
      - gateway
      - run
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/hermes:/opt/data

  web:
    image: nousresearch/hermes-agent:latest@sha256:b9f289194f7d2003745f2e8449c85c2d2ae6672d56f6e62f5fecf2e94edc6b8c
    command:
      - dashboard
      - --host
      - 0.0.0.0
      - --port
      - "9119"
      - --no-open
    restart: on-failure
    depends_on:
      - server
    volumes:
      - ${APP_DATA_DIR}/data/hermes:/opt/data
