version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: budibase_budibase_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  budibase:
    image: budibase/budibase:3.39.13@sha256:2ea12e2cdd273dea876bcf8ee3060838518d936fe6b07e4b2e5c6dbf02551397
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/budibase:/data
    environment:
      JWT_SECRET: ${APP_SEED}
