version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: budibase_budibase_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  budibase:
    image: budibase/budibase:3.34.1@sha256:e5c3726293ee578af9e1b89872172fc7ff6afb586306e53c996d2f8f8ea752e4
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/budibase:/data
    environment:
      JWT_SECRET: ${APP_SEED}
