version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: budibase_budibase_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  budibase:
    image: budibase/budibase:3.38.4@sha256:28a2c1ab7b65482c160bc7c260d2e0e864803d0e73a6f318bbb87f327977b286
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/budibase:/data
    environment:
      JWT_SECRET: ${APP_SEED}
