export APP_BITCOIN_CASH_NODE_TOR_IP="10.21.22.50"
export APP_BITCOIN_CASH_NODE_NODE_IP="10.21.21.50"

export APP_BITCOIN_CASH_NODE_RPC_PORT="8332"
export APP_BITCOIN_CASH_NODE_P2P_PORT="8335"
export APP_BITCOIN_CASH_NODE_ZMQ_HASHBLOCK_PORT="28332"
export APP_BITCOIN_CASH_NODE_RPC_USER="umbrel"
export APP_BITCOIN_CASH_NODE_RPC_PASS="$(derive_entropy "bitcoin-cash-node-rpc-pass")"
