export APP_PUBLIC_POOL_WEB_POSTGRES_USERNAME="public_pool_web"
export APP_PUBLIC_POOL_WEB_POSTGRES_PASSWORD="SlyRoundaboutWay"
export APP_PUBLIC_POOL_WEB_POSTGRES_PORT="5432"
export APP_PUBLIC_POOL_WEB_POSTGRES_DBNAME="public_pool_web_production"
# URL encode underscores (%5F) in hostname to satisfy strict URI parsing
export APP_PUBLIC_POOL_WEB_POSTGRES_HOST="public-pool-web%5Fdb%5F1"
export APP_PUBLIC_POOL_WEB_DATABASE_URL="postgres://${APP_PUBLIC_POOL_WEB_POSTGRES_USERNAME}:${APP_PUBLIC_POOL_WEB_POSTGRES_PASSWORD}@${APP_PUBLIC_POOL_WEB_POSTGRES_HOST}:${APP_PUBLIC_POOL_WEB_POSTGRES_PORT}/${APP_PUBLIC_POOL_WEB_POSTGRES_DBNAME}"
export APP_PUBLIC_POOL_WEB_REDIS_URL="redis://public-pool-web_redis_1:6379/0"
export APP_PUBLIC_POOL_WEB_MASTER_KEY="dbd1d33e19a5e0ca9b28c2c55803afef"
