version: "3.7"

services:
  server:
    image: adguard/adguardhome:v0.107.77@sha256:e6f2b8bcda06064ab055b44933a4f0e983c35558b9cdb8d2e7ab1efcee36d890
    # override the default command to set the web address to port 8095 to avoid conflict with Thunderhub
    # command from Dockerfile: https://github.com/AdguardTeam/AdGuardHome/blob/master/docker/Dockerfile
    command: ["--no-check-update", "-c", "/opt/adguardhome/conf/AdGuardHome.yaml", "-w", "/opt/adguardhome/work", "--web-addr", "0.0.0.0:8095"]
    restart: on-failure
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/work:/opt/adguardhome/work
      - ${APP_DATA_DIR}/data/conf:/opt/adguardhome/conf
    cap_add:
      - NET_ADMIN
