version: "3.7"

services:
  server:
    image: adguard/adguardhome:v0.107.78@sha256:1ea34eafe5dc691007946e8eaab7bf46b0de9412f39213d8c06e48b53bf9a6c5
    # override the default command to set the web address to port 8095 to avoid conflict with Thunderhub
    # command from Dockerfile: https://github.com/AdguardTeam/AdGuardHome/blob/master/docker/Dockerfile
    command: ["--no-check-update", "-c", "/opt/adguardhome/conf/AdGuardHome.yaml", "-w", "/opt/adguardhome/work", "--web-addr", "0.0.0.0:8095"]
    restart: on-failure
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/work:/opt/adguardhome/work
      - ${APP_DATA_DIR}/data/conf:/opt/adguardhome/conf
    cap_add:
      - NET_ADMIN
