version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sikka_web_1
      APP_PORT: 64552

  web:
    image: besoeasy/sikka:0.1.2@sha256:e54b2b00547bfbf3a2d548273535cf4f8d9674277fad7790d68b44f082a34033
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/sikka/data
