version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sikka_web_1
      APP_PORT: 8080

  web:
    image: besoeasy/sikka:0.1.0@sha256:1c210d6b7a3a36fbb88d0de27d7bc175974ba831f164ef905538fe9f5816b7eb
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/sikka/data
