version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: langflow_app_1
      APP_PORT: 7860

  app:
    image: langflowai/langflow:1.9.6@sha256:bc004d30ec7ffb64b55323ee3f87d76e9b50d114cb7a959608535420417abd2a
    user: "1000:1000"
    restart: on-failure
    environment:
      LANGFLOW_CONFIG_DIR: /app/langflow
      DO_NOT_TRACK: "true"
      LANGFLOW_DATABASE_URL: "postgresql://langflow:langflow@langflow_db_1:5432/langflow"
    volumes:
      - ${APP_DATA_DIR}/data/app:/app/langflow

  db:
    image: postgres:16.14-trixie@sha256:4b7183ac05f8ef417db21fd72d71047a4238340c261d3cc3ddb6d579ab5071ae
    user: "1000:1000"
    restart: on-failure
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
