version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellyfin_server_1
      APP_PORT: 8096
      PROXY_AUTH_ADD: "false"

  server:
    image: linuxserver/jellyfin:version-12.1ubu2604@sha256:b0b6d034aa52ed6e1a76daaa3d7ed29039d2b802a50fa8ffd1d9fc8d3fd836c7
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      # Service auto-discovery
      - 7359:7359/udp
