version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: localai_api_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/v1/*"
  api:
    image: localai/localai:v4.6.1@sha256:dfe2e6c942e32dc6dde62207a3596aea0b903d1c3b10a8dc1efc1f63eee26da7
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    environment:
      - MODELS_PATH=/models
      - LOCALAI_BACKENDS_PATH=/backends
      - LOCALAI_EXTERNAL_BACKENDS=cpu-llama-cpp
    volumes:
      - ${APP_DATA_DIR}/data/models:/models:cached
      - ${APP_DATA_DIR}/data/backends:/backends:cached
      - ${APP_DATA_DIR}/data/data:/data:cached
      - ${APP_DATA_DIR}/data/configuration:/configuration:cached
      - ${APP_DATA_DIR}/data/images/:/tmp/generated/images/
