version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitgarth_web_1
      APP_PORT: 8080

  web:
    image: bitgarth/bitgarth:0.4.2@sha256:525cedc1adb66f99c22be7c7cfc32e81a369e35eae12c5ecb6de020b76e24fe6
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      BITGARTH_CHANNEL: umbrel
