version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitgarth_web_1
      APP_PORT: 8080

  web:
    image: bitgarth/bitgarth:0.4.0@sha256:829973857bea0db864713cf39d90ac5f51a12cde4fa05b7ed6c66a84c845fe2f
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      BITGARTH_CHANNEL: umbrel
