version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: namecoin_web_1
      APP_PORT: 18080

  namecoind:
    image: ghcr.io/mstrofnone/namecoin-core-umbrel:30.2@sha256:25a08de7cd6afdc638f6295099635fc5c0bb57002ac1af4df1bcca28fc6517bd
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 15m30s
    volumes:
      - ${APP_DATA_DIR}/data/namecoind:/data/.namecoin
    environment:
      NAMECOIN_RPC_USER: umbrel
      NAMECOIN_RPC_PASS: namecoinrpc
    ports:
      - "${APP_NAMECOIN_P2P_PORT}:8334"

  web:
    image: ghcr.io/mstrofnone/namecoin-core-umbrel-web:30.2@sha256:8cb6e2dcbd82d2d5bb3ede22c6c6274cc27ddd836bc01a4743f2315619e4426f
    user: "1000:1000"
    restart: on-failure
    environment:
      NAMECOIND_HOST: namecoin_namecoind_1
      NAMECOIND_RPC_PORT: 8336
      NAMECOIND_RPC_USER: umbrel
      NAMECOIND_RPC_PASS: namecoinrpc
      PORT: 18080
    depends_on:
      - namecoind
