version: "3.7"

services:
  web:
    image: ghcr.io/athombv/homey-shs:13.3.0@sha256:d014b695a86a972b20c349ee04ab08d277acd05f82be2b8f60f640361ea20e1f
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/homey/user
