version: "3.7"

services:
  web:
    image: ghcr.io/athombv/homey-shs:13.5.1@sha256:e52125f36392e237a98d837307b14017ea0d46070d1019dd559405ce0626afe3
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/homey/user
