version: "3.7"

services:
  web:
    image: ghcr.io/athombv/homey-shs:13.5.0@sha256:64c10fa439b8395e18f063447a8ef9c08b4d273ac74b6da325f995e2640aea5e
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/homey/user
