version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: obsidian_server_1
      APP_PORT: 3000

  server:
    image: linuxserver/obsidian:1.12.7@sha256:bbc7d7fc7ad76e7fee9f90055f09b81d6bb44631fbf4fb239cbc807a5a7f26b0
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"
