version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mattermost_app_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
  
  app:
    image: alexlack/mattermost-app:v11.8.2@sha256:dd47aa39ab2ede8b201752bc524bacc5de6f1f24232a3c5e7c1af671c886c8a5
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      MM_USERNAME: admin
      MM_PASSWORD: admin
      MM_DBNAME: mattermost
      MM_SQLSETTINGS_DATASOURCE: postgres://admin:admin@mattermost_db_1:5432/mattermost?sslmode=disable&connect_timeout=10
    volumes:
      - ${APP_DATA_DIR}/data/app/mattermost/config:/mattermost/config:rw
      - ${APP_DATA_DIR}/data/app/mattermost/data:/mattermost/data:rw
      - ${APP_DATA_DIR}/data/app/mattermost/logs:/mattermost/logs:rw
      - ${APP_DATA_DIR}/data/app/mattermost/plugins:/mattermost/plugins:rw
      - ${APP_DATA_DIR}/data/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8443:8443/tcp" # WebRTC over tcp
      - "8443:8443/udp" # WebRTC over udp
    depends_on:
      db:
        condition: service_healthy

  db:
    image: alexlack/mattermost-db:v11.8.2@sha256:7d6b5cd1e7ec0e649059e4f7715b9cb0ddc6141cc0fb82fbc0e94f1d62fe7a1f
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      MM_USERNAME: admin
      MM_PASSWORD: admin
      MM_DBNAME: mattermost
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
