version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: ollama_ollama_1
      APP_PORT: 11434
      PROXY_AUTH_ADD: "false"

  ollama:
    image: ollama/ollama:0.34.2@sha256:da6e0dc5651df159e45686fd663c4dbe1624a52c44d7280eeac1551d8f865532
    environment:
      OLLAMA_ORIGINS: "*"
      OLLAMA_CONTEXT_LENGTH: 8192
      OLLAMA_VULKAN: "1"
      OLLAMA_IGPU_ENABLE: "1"
    volumes:
      - ${APP_DATA_DIR}/data:/root/.ollama
    restart: on-failure
