version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: ollama_ollama_1
      APP_PORT: 11434
      PROXY_AUTH_ADD: "false"

  ollama:
    image: ollama/ollama:0.32.15@sha256:57d60e686821ea81a7748a3ec8141308c8b8f95b27105713954abf7a6529e700
    environment:
      OLLAMA_ORIGINS: "*"
      OLLAMA_CONTEXT_LENGTH: 8192
    volumes:
      - ${APP_DATA_DIR}/data:/root/.ollama
    restart: on-failure
