version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: databag_web_1
      APP_PORT: 7000
      
  web:
    image: balzack/databag:0.1.18@sha256:37c4ab38f64842afa44ed8aea0e47271112795180708f0cb7be8ee7c7defebac
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/databag:/var/lib/databag
    environment:
      ADMIN: $APP_PASSWORD
