version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ersatztv-legacy_web_1
      APP_PORT: 8409
      PROXY_AUTH_WHITELIST: "/iptv/*,/discover.json,/device.xml,/lineup.json,/lineup_status.json"

  web:
    image: ghcr.io/ersatztv/legacy:v26.8.1@sha256:c42a0b0520668e995f5da6f42a3db939f7f0e1b3372bfc1046d650389d650bca
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/transcode:/transcode
      - ${UMBREL_ROOT}/data/storage/downloads:/media:ro
