version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ersatztv-legacy_web_1
      APP_PORT: 8409
      PROXY_AUTH_WHITELIST: "/iptv/*,/discover.json,/device.xml,/lineup.json,/lineup_status.json"

  web:
    image: ghcr.io/ersatztv/legacy:v26.9.0@sha256:c52a8e89e0e4a76364b32b02aa9c55daee69e3b5c7d77bfcd098512cf728d43a
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/transcode:/transcode
      - ${UMBREL_ROOT}/data/storage/downloads:/media:ro
