version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: kiwix_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/kiwix/kiwix-serve:3.8.2@sha256:de4d451d9d9e3e2d37c1a7b5a861698c67cc4c52c364c2a593ba554cddd6ce03
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads:/data
    command: >
      /data/*.zim -k
