version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: zeronote_app_1
      APP_PORT: 8000

  app:
    image: ghcr.io/besoeasy/zeronote:1.0.10@sha256:88a5d715b746470ef4e85196027dbd411715afdd9ee80e028c2094f1c4895095
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 5m
    environment:
      - NODE_ENV=production
