version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: zeronote_app_1
      APP_PORT: 8000

  app:
    image: ghcr.io/besoeasy/zeronote:1.0.12@sha256:208586649fcf38a86b73f2b7ed5888d71faac38729fd00c5a793ab90b09ecf2f
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 5m
    environment:
      - NODE_ENV=production
