version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: uptime-kuma_server_1
      APP_PORT: 3001
      PROXY_AUTH_ADD: "false"

  server:
    image: louislam/uptime-kuma:2.2.0@sha256:85d68948704fcadc7438f45c9f2666ef2239b5b84073479e1c5bc4d4d8b6d17c
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/uptime-kuma:/app/data
