version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: uptime-kuma_server_1
      APP_PORT: 3001
      PROXY_AUTH_ADD: "false"

  server:
    image: louislam/uptime-kuma:2.5.3@sha256:3e24e96c89efff0e3a4b0698cbdd36c15ad3022371db57166e5588853002ee5c
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/uptime-kuma:/app/data
