version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: metube_metube_1
      APP_PORT: 8081

  metube:
    image: ghcr.io/alexta69/metube:2026.04.02@sha256:db96c7de57a2563d360a0167253181773f53fc3e667de402daf31c28d4b285a0
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/metube:/downloads
    environment:
      - DELETE_FILE_ON_TRASHCAN=true
