version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: metube_metube_1
      APP_PORT: 8081

  metube:
    image: ghcr.io/alexta69/metube:2026.06.18@sha256:9bb4b82e76b45dc6f19b14f55b12c77333a02448b2f3791eb1f163ae451733bf
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/metube:/downloads
    environment:
      - DELETE_FILE_ON_TRASHCAN=true
