version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: metube_metube_1
      APP_PORT: 8081

  metube:
    image: ghcr.io/alexta69/metube:2026.09.20@sha256:36ebbfdcdfe6ee286e2b231d91c78759bb629cd283c6f75b75e1657fda2134f4
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/metube:/downloads
    environment:
      - DELETE_FILE_ON_TRASHCAN=true
