version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: syncthing_server_1
      APP_PORT: 8384

  server:
    image: syncthing/syncthing:2.1.3@sha256:8c8ff37ab6aa8be23b700648a90fa9412e214852e9fd6ea8477c8334792daec0
    restart: on-failure
    stop_grace_period: 1m
    hostname: umbrel
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/var/syncthing
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
