version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: karakeep_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/karakeep-app/karakeep:0.33.2@sha256:b069e4307dec06ea06d16989c6861c30a1ff208568be44ed5fb5d422cd3e950c
    user: 1000:1000
    restart: on-failure
    environment:
      MEILI_ADDR: http://karakeep_meilisearch_1:7700
      MEILI_MASTER_KEY: ${APP_SEED}
      BROWSER_WEB_URL: http://karakeep_chrome_1:9222
      DATA_DIR: /data
      NEXTAUTH_SECRET: ${APP_SEED}
      NEXTAUTH_URL: http://${DEVICE_DOMAIN_NAME}:8620
      KARAKEEP_VERSION: release
    env_file:
      - ${APP_DATA_DIR}/settings.env
    volumes:
      - ${APP_DATA_DIR}/data/karakeep_data:/data
    depends_on:
      - chrome
      - meilisearch

  chrome:
    image: ghcr.io/karakeep-app/karakeep-chrome:151.0.7922.47-r1@sha256:5b19bbb160e9ff60681a3abd97e1c4ec9f64212301410de658c3900ab7ef31e7
    restart: on-failure
    init: true
    command:
      - --disable-gpu
      - --disable-dev-shm-usage
      - --hide-scrollbars
      - --disable-blink-features=AutomationControlled
      - --window-size=1440,900

  meilisearch:
    image: getmeili/meilisearch:v1.41.0@sha256:860fa4baed04ae1c235de870edab0c8006227546dea1bbb6411fbfc5e27cf1db
    user: 1000:1000
    restart: on-failure
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data/meilisearch_data:/meili_data
