version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: datum-verified_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/yudikorsou/datum-verified:1.0.0@sha256:e8ad1ca0260e5d753c42dc31e99735b1480afd94c11e014ed96df6be3a7f349d
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      PORT: 8080
      DATA_DIR: /data
    volumes:
      - ${APP_DATA_DIR}/data:/data

  discord:
    image: ghcr.io/yudikorsou/datum-gateway-verify-bot:cd21dee4c86caa696c4f394f294877dbd57a3086@sha256:a19531262ee42c3f658f4fa98380ca471726a96b65574a3f69a7a2ccf6cc6893
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      SETTINGS_FILE: /data/settings.json
      DATABASE_PATH: /data/discord/bot.sqlite
    volumes:
      - ${APP_DATA_DIR}/data:/data

  telegram:
    image: ghcr.io/yudikorsou/datum-gateway-telegram-verify-bot:ffd3f27e3f1feea24fdf0a015fd01917ad6f1939@sha256:326272f91421fea30bc33cf835d0d12baf5571a9e93f6a0d4af12530c9d7058e
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      SETTINGS_FILE: /data/settings.json
      DATABASE_PATH: /data/telegram/bot.sqlite
    volumes:
      - ${APP_DATA_DIR}/data:/data
