version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: autobrr_web_1
      APP_PORT: 7474
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/autobrr/autobrr:v1.74.0@sha256:6f37217bbc0496fff0c7ffb4264545036bf735775e484188b80b31f21daa06e2
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/config
