version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: autobrr_web_1
      APP_PORT: 7474
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/autobrr/autobrr:v1.82.1@sha256:63a014b42992ada7e03fa1bbd4f02ad02d96665b172bf42106ccfcb7e23144d8
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/config
