version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: copyparty_web_1
      APP_PORT: 3923

  web:
    image: ghcr.io/9001/copyparty-ac:1.20.25@sha256:b05d9cc2c54c6295901d4e57461a6aaa3890e1a89144b31dc1cd7aa28432c245
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/config/config.conf:/cfg/config.conf:ro
      - ${APP_DATA_DIR}/data/cp_data:/cfg/hists
      - ${APP_DATA_DIR}/data/shared:/shr
      - ${APP_DATA_DIR}/data/media:/media      
    environment:
      TZ: UTC
