services:
  app_proxy:
    environment:
      APP_HOST: convertx_server_1
      APP_PORT: 3000

  server:
    image: c4illin/convertx:v0.19.0@sha256:8590a21a16adb8514a8be55b74ad0112bf58ba772328a53f7b40528fcf8fa013
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    environment:
      - HTTP_ALLOWED=true
      - ACCOUNT_REGISTRATION=true
    volumes:
      - ${APP_DATA_DIR}/data/app:/app/data
