version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: trilium-notes_server_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: triliumnext/trilium:v0.105.0@sha256:cc6a15edd7ac3df9bb98ad39dd40af8ffda6c1c0bfafe37c26137ddcbecdb7e5
    restart: on-failure
    environment:
      - TRILIUM_DATA_DIR=/data
    volumes:
      - ${APP_DATA_DIR}/data:/data
