version: "3.7"

services:
  server:
    image: esphome/esphome:2026.9.0@sha256:9959730a04c7ee38d61805681778ba5c41aa9c5d72b1ed1e910a83fa572fe18b
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure
