version: "3.7"

services:
  server:
    image: esphome/esphome:2026.3.0@sha256:5673d64947385928ae9f61e4f16eb9ad04a60cd27ff29986d54caa74c69a7925
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure
