version: "3.7"

services:
  server:
    image: esphome/esphome:2026.5.0@sha256:c0e2159c1f17f800be0f8995af801c934428598481128c8d3d6a5b3adc153dee
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure
