services:

  app_proxy:
    environment:
      APP_HOST: zigbee2mqtt_app_1
      APP_PORT: 8080

  app:
    image: koenkk/zigbee2mqtt:2.14.2@sha256:addbfb08fcef2e4477de1535636118241e10d13e898fbe4d9faba8a4d7396311
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data:rw
      - /run/udev:/run/udev:ro
    privileged: true
    environment:
      ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: "true"
      ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
      ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://mosquitto_broker_1:1883"
      Z2M_ONBOARD_NO_REDIRECT: 1
