services:

  app_proxy:
    environment:
      APP_HOST: zigbee2mqtt_app_1
      APP_PORT: 8080

  app:
    image: koenkk/zigbee2mqtt:2.14.0@sha256:c13d177dd7f7f396574ab00926188ad542cfb68c6a5d5f84021bebd9adf6ede9
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data:rw
      - /run/udev:/run/udev:ro
    privileged: true
    environment:
      ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: "true"
      ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
      ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://mosquitto_broker_1:1883"
      Z2M_ONBOARD_NO_REDIRECT: 1
