version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: mstream_server_1
      APP_PORT: 3000

  server:
    image: linuxserver/mstream:6.16.1@sha256:08f3007ba2648488c3f63926d6a8fc4969b68472fe94fbf2d9068ef472b724db
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music
