version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: mstream_server_1
      APP_PORT: 3000

  server:
    image: linuxserver/mstream:6.7.1@sha256:400fc0549f52beecf1d1e3f98196bc43b85b987a9d4086fff4f17615ea57bc71
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music
