version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: btctracker_web_1
      APP_PORT: 3000

  web:
    image: thewilqq/btc-tracker:v0.8.0@sha256:f7780ebf7e5586efebc324d4532aa768208d9f4e79b9cd048a030be8c4929df5
    restart: on-failure
    user: 1000:1000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/data/bitcoin-tracker.db
      - NEXTAUTH_SECRET=${APP_SEED}
      - NEXTAUTH_URL=http://${DEVICE_DOMAIN_NAME}:3947
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
