version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: btctracker_web_1
      APP_PORT: 3000

  web:
    image: thewilqq/btc-tracker:v0.7.0@sha256:0c7beea5e0791cc39c9294f0a62faa24aa2ef42ed04571b63977c0afe085321b
    restart: on-failure
    user: 1000:1000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/data/bitcoin-tracker.db
      - NEXTAUTH_SECRET=${APP_SEED}
      - NEXTAUTH_URL=http://${DEVICE_DOMAIN_NAME}:3947
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
