#!/usr/bin/env bash
set -euo pipefail

# Create keys for solidtime

APP_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
KEYS_FILE="$APP_DIR/keys.env"

# Check if keys.env exists and has content
if [ ! -s "$KEYS_FILE" ]; then
    echo "Solidtime keys file missing or empty. Running command to generate keys..."

    APP_KEY=$("${UMBREL_ROOT}/scripts/app" compose "${APP_ID}" run --rm app php artisan self-host:generate-keys)
    echo "${APP_KEY}" | grep -v "Container mode:" > "${KEYS_FILE}"
    
    echo "Solidtime keys file created successfully."
else
    echo "Solidtime keys file already exists and has content. No action needed."
fi

exit 0
