services:
  app_proxy:
    environment:
      APP_HOST: mqttx-web_app_1
      APP_PORT: 80

  app:
    image: emqx/mqttx-web:v1.13.1@sha256:e777a2221a4e92ea0b87b3170a96ae09d4e557d2dc80c694175669762f47cfd0
    user: "1000:1000"
    restart: on-failure
