name: Lint apps

on:
  pull_request_target:
    branches:
      - master

jobs:
  lint-apps:
    name: Lint apps
    runs-on: ubuntu-latest
    steps:
      - uses: sharknoon/umbrel-app-linter-action@d0b39f9ec5867fd001b05d5ddd6037dcc35f41bd
