version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: slink_web_1
      APP_PORT: 3000

  web:
    image: anirdev/slink:v1.10.2@sha256:22f82c454afb114e9132c8926f5c0f4d431ac25b90dc48de48b34daa0b1ca1d9
    user: "1000:1000"
    restart: on-failure
    environment:
      TZ: UTC
      ORIGIN: http://${DEVICE_DOMAIN_NAME}:8811
      REQUIRE_SSL: "false"
      USER_APPROVAL_REQUIRED: "false"
      USER_PASSWORD_MIN_LENGTH: 8
      USER_PASSWORD_REQUIREMENTS: 15
      IMAGE_MAX_SIZE: 15M
      IMAGE_STRIP_EXIF_METADATA: "true"
      IMAGE_COMPRESSION_QUALITY: 80
      STORAGE_PROVIDER: local
    volumes:
      - ${APP_DATA_DIR}/data/var:/app/var/data
      - ${APP_DATA_DIR}/data/images:/app/slink/images
