version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wizarr_app_1
      APP_PORT: 5690
      
  app:
    image: ghcr.io/wizarrrr/wizarr:v2026.3.0@sha256:c39b263499a871e3a0cd78e27cf59ca25975d99e5a9dbef18f8fae5f4c81e4cd
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - DISABLE_BUILTIN_AUTH=false
      - TZ=UTC
