version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wizarr_app_1
      APP_PORT: 5690
      
  app:
    image: ghcr.io/wizarrrr/wizarr:v2026.9.0@sha256:0627e8e13f0fa76ab3a0348153bdcba5083c9f86745299a81394b8099900758e
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - DISABLE_BUILTIN_AUTH=false
      - PORT=5690
      - TZ=UTC
