version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: openclaw_gateway_1
      APP_PORT: 18789

  gateway:
    image: ghcr.io/getumbrel/openclaw-umbrel:2026.6.5@sha256:7b8ae987ff64f8ca940d283ca847ef986c6e8b8bdef0de2217382202888bcee0
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/data/linuxbrew:/home/linuxbrew
    environment:
      APP_SEED: ${APP_SEED}
