version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: openclaw_gateway_1
      APP_PORT: 18789

  gateway:
    image: ghcr.io/getumbrel/openclaw-umbrel:2026.6.1@sha256:8b0c45a4f23e7da7c388e77f60387798f8a2303141b69531a51116cef775954e
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/data/linuxbrew:/home/linuxbrew
    environment:
      APP_SEED: ${APP_SEED}
