version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: openclaw_gateway_1
      APP_PORT: 18789

  gateway:
    image: ghcr.io/getumbrel/openclaw-umbrel:2026.3.2@sha256:7c28200a61120999a1b44797c870e2162754e4da7bf204a9877c2c8c8ea05b9a
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/data/linuxbrew:/home/linuxbrew
