version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: jellyseerr_server_1
      APP_PORT: 5055
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: ghcr.io/seerr-team/seerr:v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad
    user: "1000:1000"
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
    restart: on-failure
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
